# Generated by Django 4.1.1 on 2023-11-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_colaborators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musicians',
        ),
    ]
