# Generated by Django 4.1.1 on 2023-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='employee',
            field=models.IntegerField(default=0, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='colaborators',
            name='lastname',
            field=models.CharField(default='', max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='colaborators',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
