# Generated by Django 4.1.1 on 2023-11-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_colaborators_employee_colaborators_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='area',
            field=models.CharField(default='', max_length=200, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='colaborators',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='colaborators',
            name='position',
            field=models.CharField(default='', max_length=200, verbose_name='Puesto'),
        ),
    ]
