# Generated by Django 4.1.1 on 2023-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_colaborators_area_colaborators_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='asistencia',
            field=models.BooleanField(default=False, verbose_name='Asistencia'),
        ),
    ]
