# Generated by Django 4.1.1 on 2023-11-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_colaborators_email_colaborators_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborators',
            name='lastname',
        ),
    ]
