# Generated by Django 4.1.1 on 2023-11-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_colaborators_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborators',
            name='asistencia',
            field=models.CharField(default='Pendiende', max_length=100, verbose_name='Asistencia'),
        ),
    ]
