# Generated by Django 4.1.1 on 2023-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_colaborators_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0, verbose_name='Celular')),
                ('employee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Employee ID')),
                ('ticket', models.TextField(blank=True, null=True, verbose_name='Ticket')),
            ],
        ),
    ]
