# Generated by Django 4.1.1 on 2023-11-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_whatsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborators',
            name='employee',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Employee ID'),
        ),
    ]
