# Generated by Django 4.1.1 on 2023-11-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_colaborators_noi_alter_colaborators_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborators',
            old_name='NOI',
            new_name='Noi',
        ),
    ]
