# Generated by Django 4.1.1 on 2023-11-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_noi_colaborators_noi'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='known',
            field=models.BooleanField(default=False, verbose_name='Known'),
        ),
    ]
