# Generated by Django 4.1.1 on 2023-11-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_colaborators_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborators',
            name='location',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Planta'),
        ),
    ]
