# Generated by Django 4.1.1 on 2023-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_colaborators_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborators',
            name='taxi',
            field=models.BooleanField(default=False, verbose_name='Taxi'),
        ),
    ]
