# Generated by Django 4.1.1 on 2023-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_colaborators_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborators',
            name='phone',
            field=models.BigIntegerField(default=0, verbose_name='Celular'),
        ),
    ]
